### PR TITLE
Add login link in public votes

### LINKED ISSUE #852: LogIn Option
**Is your feature request related to a problem? Please describe.**
When not logged there is no possibility to do so. You are forced to choose a nickname. To log in with my nextcloud username I have to do so separately.

**Describe the solution you'd like**
A log in option beneath the 'choose a name' panel.

**Describe alternatives you've considered**
Loading the main site.

**Additional context**
-
Poll Ver:  1.3.0
Nextcloud Ver: 17.0.3

### PR DESCRIPTION
**Pull request by dartcafe**
fixes #852 See issue for screenshot.

### CODE REVIEW

**Comment by v1r0x** [comment]
Your solution to generate the link didn't work for me, because my instance is running in a subfolder.
The `generateUrl` helper takes care of that.

**Comment by dartcafe** [comment]
@v1r0x Ehm. I merged accidentially.

**Comment by v1r0x** [comment]
But you switched to `OC.generateUrl`? Then I'm ok with your merge ;)

**Comment by dartcafe** [comment]
Wasn't it your commit? 
https://github.com/nextcloud/polls/pull/857/commits/3a6e8b1c02cc87ffdb4d4d759e4476f32f46dafe

**Comment by v1r0x** [comment]
You are right :sweat_smile: I thought I only suggested it :D

**Comment by dartcafe** [comment]
No comment. :-)

**Pull request merged**
