### PR TITLE
Added 0.8.0 changelog

### PR DESCRIPTION
**Pull request by splitt3r**
Used http://keepachangelog.com/en/1.0.0/ format.

### CODE REVIEW

**Comment by splitt3r** [comment]
@v1r0x [this](https://github.com/nextcloud/polls/issues/169) one?

**Comment by v1r0x** [comment]
@splitt3r Exactly

**Comment by dartcafe** [comment]
I added some milestones to different PRs and Issues. For future releases, we shpuld use the milestones, so the changelog has a good reference. 
https://github.com/nextcloud/polls/milestone/7?closed=1
Not every item is for the changelog, but it helps to remember. :-)

**Comment by splitt3r** [comment]
@v1r0x messeg it up a bit :sweat: please create a squash commit

**Comment by v1r0x** [comment]
@splitt3r How can I squash your commits?

**Comment by splitt3r** [comment]
Didn´t tried it yet ^^ but there it is: 

Squash

**Pull request merged**
