### PR TITLE
[stable-6] use bamarni/composer-bin-plugin instead of global tools

### PR DESCRIPTION
**Pull request by come-nc**
Backport of #3390

Psalm in my stable-6 PR was giving weird errors, so backporting this to get the same setup as master which is working.

### CODE REVIEW

**Comment by come-nc** [comment]
```
Error: lib/Db/Poll.php:349:18: PossiblyUnusedMethod: Cannot find any calls to method OCA\Polls\Db\Poll::getIsCurrentUserLocked (see https://psalm.dev/087)
Error: lib/Middleware/RequestAttributesMiddleware.php:43:47: UndefinedClass: Class, interface or enum named OCP\AppFramework\Http\Attribute\PublicPage does not exist (see https://psalm.dev/019)
Error: lib/Model/Settings/AppSettings.php:69:18: PossiblyUnusedMethod: Cannot find any calls to method OCA\Polls\Model\Settings\AppSettings::__construct (see https://psalm.dev/087)
Error: lib/Db/Poll.php:0:0: UnusedBaselineEntry: Baseline for issue "PossiblyUnusedMethod" has 1 extra entry. (see https://psalm.dev/316)
Error: lib/Model/UserBase.php:0:0: UnusedBaselineEntry: Baseline for issue "PossiblyUnusedMethod" has 1 extra entry. (see https://psalm.dev/316)
```

Cannot really fix those right now as it would conflict with #3480 and #3503 , so I will wait for them to be merged and rebase before fixing.

**Comment by dartcafe** [comment]
Just update the baseline and it should be quiet. 
`composer run psalm:baseline` and `psalm:baseline:update`

**Comment by come-nc** [comment]
> Just update the baseline and it should be quiet. `composer run psalm:baseline` and `psalm:baseline:update`

Did that for everything but the `PublicPage` error, which was a real one. Ready for review.

**Comment by AndyScherzinger** [comment]
given the backporting of v7 to older Nc versions I suppose this PR can be closed? @come-nc

**Comment by come-nc** [comment]
Yep, fine by me.

**Pull request closed without merging**
