### PR TITLE
Version 1.2

### PR DESCRIPTION
**Pull request by dartcafe**
main changes in this release:
 - internal optimizations
 - in public poll ask for username in a modal
 - Allow site user to vote in hidden poll via public link (#779)
 - New option: Allow admins to edit poll
 - Prevent deleted poll from beeing called via public link (#773)
 - Present error page, when poll cannot be accessed (#772)
 - Allow site user to access hidden poll, when called via public link (#779)
 - Give permant access to votes, the user voted in
 - New filter: participated - Polls, where the user participated in
 - delete comments (#193)
 - Enter user name in public shared polls in a modal
 - fixed routing error in NC16 (#787)
 - load subscription on route change (#788)

internals
 - updated dependencies
 - eleminating publicVote.vue and use vote.vue for public votes
 - consolidated routes (PageController)
 - update to nextcloud 1.3.0
 - minor UX optimizations

### CODE REVIEW

**Comment by dartcafe** [comment]
@v1r0x Another week another release. 😁 Wanted to get rid of some issues before resting a while. So If you can make a review, the branch is ready to be merged to master. We should wait for some days, to give the translations a chance.

**Comment by Dennis1993** [comment]
I've installed the neu version and it is much better for new user with the modal window to enter the name! Good job!

I don't know how long the translation needs, I post some not correct translations here. I don't know if its fixed then you can ignore it :)

image


image

**Comment by dartcafe** [comment]
Translations are only triggered from and added to the master branch.

**Comment by tortuetorche** [comment]
Hi @dartcafe,

> Translations are only triggered from and added to the master branch.

FYI, the `Shift all date options` options are not translated and translatable in [Transifex](https://www.transifex.com/nextcloud/nextcloud/translate/#fr/polls/).

References:
* `master` branch: https://github.com/nextcloud/polls/blob/217492e10f2a633ecd7fb3bd4b91a72df7fd3148/src/js/components/SideBar/SideBarTabOptions.vue#L49
* `version-1.2` branch: https://github.com/nextcloud/polls/blob/version-1.2/src/js/components/SideBar/SideBarTabOptions.vue#L53

Have a good day,
Tortue Torche

**Comment by dartcafe** [comment]
> FYI, the `Shift all date options` options (_minute_, _hour_, _day_, _week_, _month_, _year_) are not translated

Yep. Correct, because the array is also used as key for the shift span. If you mind, you could create an issue for that.

**Comment by dartcafe** [comment]
@v1r0x It seems, everything is working well. I will merge this PR, so the translations can be added.

**Pull request merged**
