### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by dartcafe**
@v1r0x Are you able to compile the release shortly?

### CODE REVIEW

**Comment by v1r0x** [comment]
I plan to test and release tomorrow evening. Please ping me again, if there is no release on monday :)

**Comment by dartcafe** [comment]
Finished for now. If you are ready, you can merge and build from the master

**Comment by dartcafe** [comment]
Ehm. OK. 🤣

**Comment by v1r0x** [comment]
Already done 😝 Upload to appstore is on the way

Feel free to edit the changes on the release page :)

**Comment by v1r0x** [comment]
Upload to appstore seems to be broken (at least for me). Will try again tomorrow.

**Comment by v1r0x** [comment]
1.0 is in the appstore now! 🤘 🎉

**Pull request merged**
