### PR TITLE
Repckaging for #532

### PR DESCRIPTION
**Pull request by dartcafe**
To do:
- [x] Update release date in CHANGELOG.md before release

### CODE REVIEW

**Comment by dartcafe** [comment]
@v1r0x Can you test the release before publishing, if #532 is fixed after update modules?

**Comment by v1r0x** [comment]
Couldn't test it...CSP blocks fonts and doesn't load polls. Force-reload/private windows won't work either

**Comment by dartcafe** [comment]
Ist it possible, that a browser extension causes this? i.e. vue-devtools?

**Comment by v1r0x** [comment]
No, it's a new VM with only nextcloud installed. I can try another system tomorrow. Fingers crossed this works....Debugging is a nightmare in NC

**Comment by dartcafe** [comment]
is it like #531?

**Comment by v1r0x** [comment]
Yes, same problem as in https://github.com/nextcloud/polls/issues/531#issuecomment-467078847
I tried it on another machine and the build looks good. Disabled and removed the old polls version and enabled/installed the new build

**Comment by dartcafe** [comment]
@v1r0x Would you add the release date to the readme and fire this up?

**Pull request merged**
