### PR TITLE
Update max-version to current dev version 16

### PR DESCRIPTION
**Pull request by jancborchardt**
This is necessary to make the Polls app work on the current master / dev version of Nextcloud which is version 16. :)

Please review @dartcafe @splitt3r @v1r0x

### CODE REVIEW

**Comment by jancborchardt** [comment]
@dartcafe @v1r0x we should also have a release, so it works on Nextcloud 15 via the app store? https://apps.nextcloud.com/apps/polls :)

**Comment by v1r0x** [comment]
> Haha! :D You should sync it with some software maybe? wink Anyway, @rullzer @MorrisJobke how can @v1r0x get a new one?

Good idea, but can't think of a reliable and nice software to do this... :stuck_out_tongue_closed_eyes: 
Already have a PR for a new key: https://github.com/nextcloud/app-certificate-requests/pull/205 maybe everyone is busy wrapping christmas gifts :)

**Comment by dartcafe** [comment]
> Good idea, but can't think of a reliable and nice software to do this...

What about Keybase?

**Comment by jancborchardt** [comment]
I think there’s also a thing called "Boxdrop" or so I heard …

**Pull request merged**
