### PR TITLE
Explicit close a poll

### LINKED ISSUE #1156: Support explicit closing a poll and avoid the misleading term expired
The term `expired poll` could mislead users, if a poll was closed by the owner via setting the current moment as expiry date. In this case no announced expiry time was announce before. This can cause confusion.

- [x] Add a button to explicitly close the poll
- [x] Change the term `expiry `to `closing date`
- [x] Change the term `expired` to `closed`
- [x] replace items
- [x] Change intial closing date to 1 week in advance
- [x] Change route names
- [x] Change properties and methods

### PR DESCRIPTION
**Pull request by dartcafe**
fix #1156

### CODE REVIEW

**Review by v1r0x — APPROVED** [review]
👍 🐧

**Comment by dartcafe** [comment]
Initial status
grafik


Poll is closed, regardless, if expired or explicit closed via close button
grafik

grafik

Open poll with closing date
grafik
grafik

Changed navigation icon and capture
grafik

**Comment by dartcafe** [comment]
> 
> 
> 👍 🐧

5 minutes!  😲

**Comment by dartcafe** [comment]
Done! Another review?

**Comment by jancborchardt** [comment]
Hi @dartcafe @v1r0x by the way, we have a Nextcloud Talk instance where we also invite community members. There is a general "Community chat" room, but also app-specific rooms – we could create one for "Polls team" so you can communicate and build a bigger community. :) Let me know if you’d like to be added there, I can invite you with a guest account via your email addresses from your commits?

(cc @kesselb)

**Comment by dartcafe** [comment]
@jancborchardt Don't hijack closed issues. 😁 
@kesselb also invited me via help.nextcloud.com. Would be great, if you add an account.

**Pull request merged**
