### PR TITLE
use $schemaClosure in migration

### LINKED ISSUE #2980: App doesn't cooperate with `occ db:convert-type`
### ⚠️ This issue respects the following points: ⚠️

- [ ] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When converting to another db type, the tables are not created and therefore not converted.

In

https://github.com/nextcloud/polls/blob/0a8c7451b33c962db01ad65599ca5166421096ce/lib/Migration/Version050100Date20230515083001.php#L48

`$schemaClosure` is not used and therefore migration to a different schema/database is currently not supported.

### What did you expect, how polls should behave instead?

Well, the app should cooperate by using `$schemaClosure` and return the schema (OC\DB\SchemaWrapper) the closure returns. See https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html
If it does that, it shouldn't do
https://github.com/nextcloud/polls/blob/0a8c7451b33c962db01ad65599ca5166421096ce/lib/Migration/Version050100Date20230515083001.php#L51
since Nextcloud`s MigrationService takes care of the rest (e.g. uses the correct connection). I have tested this and it fixes the issue.

### What steps does it need to replay this bug?

1. use `occ db:convert-type`
2. observe rows `oc_polls_...` under "The following tables will not be converted:"

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

First time installation

### Affected polls version

5.1.0

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

_No response_

### Add your browser log here

_No response_

### Additional client environment information

_No response_

### NC version

Nextcloud 26 (Nextcloud Hub 4)

### Other Nextcloud version

_No response_

### PHP engine version

PHP 8.1

### Other PHP version

_No response_

### Database engine

MariaDB

### Database Engine version or other Database

11.0.2

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

_No response_

### Additional environment informations

_No response_

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by notEvil**
fixes #2980

Please note that I'm not particularly familiar with php and the codebase in general. The solution is a proposal.

### CODE REVIEW

**Comment by notEvil** [comment]
No, because in the context of convert-type it is has to operate on a different database. During migration, the class gets instantiated only once, remembering the source schema (say SQLite) in the process. However, it then needs to create the tables on the target schema (say Postgres) using the target connection. So it needs to delegate the actual execution to Nextcloud.

**Comment by dartcafe** [comment]
Thanks for contribution!!

**Comment by dartcafe** [comment]
> Please note that I'm not particularly familiar with php and the codebase in general.

Fun fact. I am not even a programmer and had no clue of PHP or JS when I started contributing here .

**Comment by notEvil** [comment]
Interesting :)

Regarding the failed check:
https://github.com/nextcloud/server/blob/e9ac0287f2b7d4da856bec416a282c8fc4c7feab/lib/private/DB/MigrationService.php#L444C3-L444C3
passes a `OC\DB\SchemaWrapper` but declares it as `OCP\DB\ISchemaWrapper`. And my quick and dirty solution was to not care about the type. This is where someone with more experience immediately knows what to do about it, closing the circle.

**Comment by dartcafe** [comment]
Erks. I think, we need another approach. I will come back to it later. Currently I'm rather busy.

**Comment by dartcafe** [comment]
Superseded by #3024

**Pull request closed without merging**
