### PR TITLE
fix: Display circle share activities correctly

### PR DESCRIPTION
**Pull request by hamza221**
| b | a |
|--------|--------|
| image | image |

### CODE REVIEW

**Review by dartcafe — APPROVED** [review]

**Comment by hamza221** [comment]
@dartcafe  I couldn't find stable-7 do you release 7 from master?

**Comment by dartcafe** [comment]
There is no need for backport. The current master supports all necessary Nextcloud releases.

**Comment by dartcafe** [comment]
Funny is: I did not know, that the backports work for this branch. 🤣

**Pull request merged**
