### PR TITLE
Add SPDX header

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* replacing former license headers with standardized and unified SPDX headers
* adding a GH action to check any future PRs for compliance
* unified header => move any author to the newly added `AUTHORS.md`
* Add Badge to the readme reflecting the current compliance status of the main branch

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@dartcafe as mentioned the last days on the chat, here is the PR moving things to standardized SPDX headers - looking forward to your feedback as well @v1r0x

**Comment by AndyScherzinger** [comment]
Since the questions came up on the use of a generic spdx header:

* https://reuse.software/faq/#many-copyright-statements
* https://reuse.software/faq/#when-copyright

In essence: many people when having been asked how to deal with adding such headers voted in favor of the generic solution and an authors-list file. So PRs aren't polluted with header changes and folks aren't sending PRs which just change dates on copyright headers because it is a new year.

**Review by dartcafe — APPROVED** [review]
Fine for me.

**Review by dartcafe — CHANGES_REQUESTED** [review]
Sorry to interrupt
Ist it possible to keep the first Autor aka copyright holder and the initial publishing date?

**Comment by AndyScherzinger** [comment]
@dartcafe can you clarify a bit more? 

To comment on your request:
* all files should have a date and that date should always be the year of the initial commit of that file
* the first author is not the copyright holder, all authors are, so while one could add the first committer with an explicit copyright line, all other contributors also have a copyright. The same way the initial author has -> to the lines of code they contributed to that specific file. Hence I would argue to not add the first committer explicitely

**Comment by dartcafe** [comment]
My point was just to respect the historical usage of the copyright entry. For me personally it is not important. 
Thanks for the explanation.

**Review by dartcafe — DISMISSED** [review]

**Comment by dartcafe** [comment]
@v1r0x Do you have any comment for this change? Otherwise I would ask @AndyScherzinger for merging this PR.

**Comment by dartcafe** [comment]
Before we rebase frequently and in preparations for the upcomming changes, I vote for merging this.

**Comment by AndyScherzinger** [comment]
> Before we rebase frequently and in preparations for the upcomming changes, I vote for merging this.

Fine by me of course. The reason I rebased were conflicts with the main branch and newly added files on master that didn't have SPDX headers. So while the PR is CI-green, after merging it to the main branch, any other newly created PR would be red given the REUSE Github action that would than fail.

**Comment by AndyScherzinger** [comment]
I would also say "can be merged", worst case we revert things _or_ create follow-up PRs

**Comment by dartcafe** [comment]
Currently there are no relevant PRS targeting master. That's because "now" is a good time.

**Comment by AndyScherzinger** [comment]
Yes, again, fine to be merged from my pov - of course 👍

**Comment by dartcafe** [comment]
🤣 I assumed the author merges, not the reviewer.

**Comment by AndyScherzinger** [comment]
Ah, alright. I thought you would decide to merge at some point if @v1r0x wouldn't reply 😅

**Comment by AndyScherzinger** [comment]
In any way, very happy to have it in 🎉

**Comment by dartcafe** [comment]
@AndyScherzinger 
How to deal with this??? 
https://github.com/nextcloud/polls/actions/runs/9450484914

**Comment by AndyScherzinger** [comment]
@dartcafe like this: #3555

**Pull request merged**
