### PR TITLE
create hashes before deleting invalid entries

### PR DESCRIPTION
**Pull request by dartcafe**
related #3280

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Didn't test but makes sense if Nextcloud keeps the order

**Comment by dartcafe** [comment]
I rely on it, otherwise the repair steps would not be predictable.

**Comment by lookup82** [comment]
Unfortunately, I have performed the update and cannot roll it back. Can I retrieve the surveys? I have backups available.
From the administration menu, some surveys can be seen; could this be useful?

**Comment by dartcafe** [comment]
It is the options and votes, which got deleted. You can rollback from a db backup and then call occ polls:db:rebuild. 

The command works in the correct order, other than the repair steps and should create the hashes.

**Comment by dartcafe** [comment]
@v1r0x Are you able to update the version in the app store, before more users run into the problem?

**Comment by lookup82** [comment]
> It is the options and votes, which got deleted, so the polls themself are still there. You can rollback from a db backup (tables `oc_options` and `oc_votes` should be enough and then call occ polls:db:rebuild.
> 
> The command works in the correct order, other than the repair steps and should create the hashes.

Performing these operations does not seem adequate; I am investigating further.

mysqldump -u nextcloud -p nextcloud oc_polls_options oc_polls_votes  > backup_polls.sql
mysqldump -u nextcloud -p nextcloud < backup_polls.sql
occ polls:db:rebuild

**Comment by lookup82** [comment]
I am not sure if `oc_options` and `oc_votes` were empty even before performing the restore from the old database.

Nonetheless, I encountered the following error in the log:
`json_decode(): Argument #1 ($json) must be of type string, null given in file '/var/www/nextcloud/apps/polls/lib/Db/Preferences.php' line 71`

I resolved the issue following a suggestion I found in this comment: https://github.com/nextcloud/polls/issues/3283#issuecomment-1917905262

Thanks to all 🙏🏻

**Pull request merged**
