### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by dartcafe**

### CODE REVIEW

**Comment by dartcafe** [comment]
@splitt3r I created a rc branch with flexbox-1 merged. In th end we have some conflicts, but I am away the next days. Can you review it?

**Comment by v1r0x** [comment]
@dartcafe Is this a duplicate of #171 for the rc-0.8 branch?

**Comment by splitt3r** [comment]
@v1r0x @dartcafe i think repo members should be able to change the destination branch of my pr instead of creating a new one :) Anyway i will review the conflicts 👍

**Comment by v1r0x** [comment]
> @v1r0x @dartcafe i think repo members should be able to change the destination branch of my pr instead of creating a new one :) Anyway i will review the conflicts :+1:

Yes, changing the destination is possible. Should I close this one and change #171 to rc-0.8? @dartcafe @splitt3r

**Comment by dartcafe** [comment]
The rc-0.8 branch is for testing the compatibility of the PRs. I did not touch the original PRs and merged the flexbox-1 branch via #176 (duplicate of #166) and created #177 (duplicate of #171). The result are not resolvable conflict in the mentioned files. 

I expected tha, because I made heavy changes and the changes from @splitt3r are not resolvable automatically (i.e. goto and main). 

I didn't want to touch #171.

**Comment by splitt3r** [comment]
I merged the two branches :) we should be able to merge the refactor into RC branch now. But let´s do it in #171 by changing the destination. That way we can test the RC branch and finally if everything goes well merge the RC branch into the master. That´s near to the git flow 😀.

**Pull request closed without merging**
