### PR TITLE
Dashboard widget to list relevant polls

### PR DESCRIPTION
**Pull request by Tiller**
I developed a simple dashboard widget for personal use. I guess it doesn't hurt to share it with the community!

image

Note: I can take some feedback into account, but I might not be very active on this PR. If anyone wants to take over the PR to improve / fix / ... feel free

### CODE REVIEW

**Comment by Raudius** [comment]
Moving the discussion over from https://cloud.nextcloud.com/call/xs25tz5y

Its possible your node/npm version is not playing nice with the dependencies. For me the lint command works with node 14.0.0 and npm 7.24.2.

```
$ npm run lint

> polls@4.0.0 lint
> eslint --ext .js,.vue src


/home/raul/repos/nextcloud-polls/src/js/views/Dashboard.vue
   3:4   error  Trailing spaces not allowed                                                                            no-trailing-spaces
  23:1   error  Expected "\t" character, but found " " character                                                       vue/html-indent
  70:3   error  The "NcButton" component has been registered but not used                                              vue/no-unused-components
  71:3   error  The "PlusIcon" component has been registered but not used                                              vue/no-unused-components
  72:3   error  The "PollItem" component has been registered but not used                                              vue/no-unused-components
  81:1   error  Expected indentation of 3 tabs but found 12 spaces                                                     indent
  82:1   error  Expected indentation of 2 tabs but found 8 spaces                                                      indent
  90:21  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  97:3   error  Expected catch() or return                                                                             promise/catch-or-return
  97:43  error  Each then() should return a value or throw                                                             promise/always-return

✖ 10 problems (10 errors, 0 warnings)
  5 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by Tiller** [comment]
Indeed, switching to your node/npm version did the trick thanks. Is there somewhere a list of recommended versions?

**Comment by Raudius** [comment]
>  Is there somewhere a list of recommended versions?

Usually you can check the `package.json` for the engines:
```json
"engines": {
	"node": "^16.0.0",
	"npm": "^7.0.0 || ^8.0.0"
}
```

Just the DCO check now :stuck_out_tongue:

**Comment by dartcafe** [comment]
@Tiller Thanks for your contribution. Just start a review request and add the review label, if you think it is mergable.

**Comment by Tiller** [comment]
> @Tiller Thanks for your contribution. Just start a review request and add the review label, if you think it is mergable.

Hi, I don't know how to do any of that 😅 I've tried to look around, and I don't seem to be able to do any of that. No edit button allows me to add new labels and can't find any action loosely related to a review request.

**Review by dartcafe — APPROVED** [review]
lgtm

**Comment by dartcafe** [comment]
Cool work, thanks a lot. Saved me some work. 👍

**Pull request merged**
