### PR TITLE
Hide deprecated projects in sidebar by default

### PR DESCRIPTION
**Pull request by Pytal**
Deprecate projects which is superseded by Related resources https://github.com/nextcloud/server/issues/28320

### CODE REVIEW

**Comment by dartcafe** [comment]
And I had so much fun with implementing projects. 😉 
I scheduled that to version 4.0, which will come shortly after the 3.8.0-release. Too many breaking changes in NC25.

**Review by dartcafe — CHANGES_REQUESTED** [review]
This is just to block merging to the master branch too early.

**Review by dartcafe — CHANGES_REQUESTED** [review]
@nextcloud/initial-state is missing as module

**Comment by dartcafe** [comment]
@Pytal I added `@nextcloud/intial-state`

But `loadState('core', 'projects_enabled', false)` always returns `false`, regardless what I define in the config file (`'projects.enabled' => true,`). NC25-beta3

**Comment by Pytal** [comment]
From the commits this looks like it needs a rebase first @dartcafe

**Comment by dartcafe** [comment]
> From the commits this looks like it needs a rebase first @dartcafe

I did.

**Comment by dartcafe** [comment]
@Pytal I think, I messed this pr up. Maybe you could restart in a fresh branch from ne current master branch? 

But I still have the problem, that I cannot activate projects to test it.

**Comment by Pytal** [comment]
> @Pytal I think, I messed this pr up. Maybe you could restart in a fresh branch from ne current master branch?
> 
> But I still have the problem, that I cannot activate projects to test it.

No worries, feel free to apply this commit https://github.com/nextcloud/polls/pull/2544/commits/895d754d9a1a21ef5d710d7c893ed8f23a67912f in another PR and testing it on https://github.com/nextcloud/server `master` branch should work

**Comment by dartcafe** [comment]
closed in favour of #2585

**Pull request closed without merging**
