### PR TITLE
ci: Add release automation workflow

### PR DESCRIPTION
**Pull request by ChristophWurst**
This workflow will be used to build packages at https://github.com/nextcloud-releases/polls

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by dartcafe** [comment]
I think I understand the code. But please help me understand. 
* If I understood this right, the action triggers upon published releases, right?
* Does the app storre release differ main releases from beta and alpha?
* Where are the secrets stored? I could not find them.

**Comment by AndyScherzinger** [comment]
> I think I understand the code. But please help me understand.
>
> * If I understood this right, the action triggers upon published releases, right?

The code gets pushed to the re.ease-org repo variant which than triggers the publishing to the store

> * Does the appstore release differ main releases from beta and alpha?

app store itself distinguishes releases stable/beta via the existence of a suffix i.e. -beta -alpha -rc etc.

> * Where are the secrets stored? I could not find them.

Within the GH organisation itself, hence hidden to people but accessible to the GH action itself

> * How are the release notes added to the appstore?

Don't know, maybe @ChristophWurst does

**Comment by ChristophWurst** [comment]
The app store reads the CHANGELOG.md file, ref https://nextcloudappstore.readthedocs.io/en/stable/developer.html#changelog. Release notes on github are not picked up by the automation nor the app store.

**Comment by ChristophWurst** [comment]
> Where are the secrets stored? I could not find them.

At https://github.com/nextcloud-releases/polls

The release is done as follows

1. Get the app release-read in this repo. Everything has to be in git. E.g. version bump, changelog update.
2. Create a git tag. Push it to this repo *and* https://github.com/nextcloud-releases/polls
3. Open the tags/releases page at https://github.com/nextcloud-releases/polls and create a new release
4. Open https://github.com/nextcloud-releases/polls/actions and see the release workflow running

**Comment by ChristophWurst** [comment]
@AndyScherzinger @dartcafe are there any stable branches you want to release from?

**Comment by AndyScherzinger** [comment]
Currently we should be fine since `master`===v7, however `next`===v8, so we need to forward-port this one I think

**Pull request merged**
