### PR TITLE
Add 'Ask for feedback on PRs '

### PR DESCRIPTION
**Pull request by hamza221**

### CODE REVIEW

**Review by dartcafe — COMMENTED** [review]
This makes no sense here, since this app is not maintained by Nextcloud

**Comment by ChristophWurst** [comment]
> This makes no sense here, since this app is not maintained by Nextcloud

@DaphneMuller ^

**Comment by DaphneMuller** [comment]
the app is in our spreadsheet though with Hamza as contact person, so please figure that out with Andy if needed and otherwise please merge :)

**Comment by hamza221** [comment]
Even though Polls is primarily maintained by community namely @dartcafe, it can still provide insight how Nextcloud as a company is seen from a supporting side for contributors.

**Comment by hamza221** [comment]
@dartcafe the failing check is unrelated right?

**Comment by dartcafe** [comment]
> @dartcafe the failing check is unrelated right?

Yep. Was afailed container. Re-run fixed it

**Review by dartcafe — APPROVED** [review]

**Comment by dartcafe** [comment]
@hamza221 Are you aware, thet this action dies before all issues/prs are processed? 

Does it make sense, that all issues starting by no. 1 are processed?

```console
Batch  #29  processed.
Processing the batch of issues  #30  containing  100  issues...
Warning: No more operations left! Exiting...
Warning: If you think that not enough issues were processed you could try to increase the quantity related to the  operations-per-run (​[https://github.com/actions/stale#operations-per-run​)](https://github.com/actions/stale#operations-per-run%E2%80%8B))  option which is currently set to  30
Statistics:
Processed items: 2900
├── Processed issues: 1056
└── Processed PRs   : 1844
Fetched items: 3000
Operations performed: 30
```
https://github.com/nextcloud/polls/actions/runs/8461346634/job/23180971213#step:3:17213

**Comment by hamza221** [comment]
cc @marcelklehr

**Pull request merged**
