### PR TITLE
Disallow to allow

### PR DESCRIPTION
**Pull request by dartcafe**
Change "Disallow maybe" to "Allow maybe".

### CODE REVIEW

**Comment by dartcafe** [comment]
Tested migration and fresh installation. All OK.

**Comment by dartcafe** [comment]
@v1r0x I will merge. If you are ready, you can fire the release.

**Comment by herrmannsdorfer** [comment]
This PR breaks the polls.app with NC 14.0.4. I pulled the latest master from GIT five minutes ago and now I experience the following errors:
bildschirmfoto 2018-12-12 um 11 40 05
Polls app is unusable at the moment. You cannot access existing polls or create new ones.
Polls app that was upgraded was 0.9.1 RC2. I upgraded to the latest master on the CLI (git clone https://github.com/nextcloud/polls.git).

**Comment by v1r0x** [comment]
> * Delete all polls related tables from the database
> * Delete all polls related entries in the migration table

:confused: The migration should run without deleting all polls.

**Comment by herrmannsdorfer** [comment]
Sorry folks, I have no interest in losing existing data with this update. I rolled back to a working snapshot and will wait for a release that covers this migration issue. I already opened #443 for it.

**Comment by dartcafe** [comment]
From which version did you update? Migration works from 0.8 release.

**Comment by dartcafe** [comment]
> 😕 The migration should run automatically without deleting all polls.

That was relating the test, if you switched the branches, because, there was an incompatibility between them.

**Pull request merged**
