### PR TITLE
Favicons

### PR DESCRIPTION
**Pull request by dartcafe**
Added favicons and removed 	unnecessary tags from svgs

### CODE REVIEW

**Comment by splitt3r** [comment]
Could you adjust the border of the favicon. Seems to be 1px bigger for all of the other apps.

Favicons

**Comment by dartcafe** [comment]
@splitt3r 
gave the hight of the bars 2px less and lifted them for one pixel. Please check, if the icons work.

**Comment by v1r0x** [comment]
@dartcafe could you do something similar for the width? And what are these small points on the icon? 😁

**Comment by dartcafe** [comment]
I will adjust the width one pixel too. But I have a strange behavior: 
When I diable the theming app, the icon is displayed as favicon, when I enable it, it disapears. 

I don't have the pixels, I believe this are marks from @splitt3r.

**Comment by splitt3r** [comment]
These strange dots appear in ff for me. :grimacing: dont know why will habe a look at it.

**Comment by dartcafe** [comment]
I adjusted the height and width to the dimensions, which the calender app uses. Please test....

**Comment by splitt3r** [comment]
I still have these strange dots in FF :/ perhaps some strange scaling issue. Looks a bit strange that the bars are not centered on the blue background 😁

**Comment by dartcafe** [comment]
Strange. I don't understand how the theming app works, the icons are not updated, when I chaged them. I copied the icons manually into the data-dir and then they are displayed correctly.

**Comment by dartcafe** [comment]
Changing the colors in the theme recreates the icons.

**Pull request merged**
