### PR TITLE
Add display names

### PR DESCRIPTION
**Pull request by dartcafe**
Show displayName instead of userId #715

### CODE REVIEW

**Comment by herrmannsdorfer** [comment]
`displayName` is now shown everywhere except in the header:

Screenshot 2020-01-29 at 16 58 16

And the log reads:

Screenshot 2020-01-29 at 17 03 28

Notification is not sent.

**Comment by dartcafe** [comment]
Had some trouble with the userBubble component. Is fixed. I'll wait for some bugs to fix before makint the final RC of Polls 1.2

**Comment by dartcafe** [comment]
Notification are working on my side. There was an error in the route. Maybe, the job is paused. Normally it will resume automatically after timeout. Otherwise look in the OC_Jobs table and set all timestamps (`last_run` and `last_checked`) of the job `OCA\Polls\Cron\NotificationCron` to zero.
If there is an entry under `reserved_at`, the cron is paused because of errors. Set it to zero and it will be queued again.

**Comment by herrmannsdorfer** [comment]
Confirmed. Notifications work. But ...

Activity notification still uses userId instead of displayName :-)
Screenshot 2020-01-30 at 09 35 40

**Comment by dartcafe** [comment]
Missed that ones.

**Pull request merged**
