### PR TITLE
Develop 0.9

### PR DESCRIPTION
**Pull request by dartcafe**

### CODE REVIEW

**Comment by dartcafe** [comment]
@splitt3r Travis fails, because the install script seems not to know NC14. Are you able to fix this?

**Comment by dartcafe** [comment]
Umpf. Forget it. I found the variable...

**Comment by jospoortvliet** [comment]
Pretty big overhaul, I look forward to the result!

Why not call it 1.0? Also, if you want to have a nice blog on our site about this release, please shoot me an email! I'd love to promote it a bit.

**Comment by jospoortvliet** [comment]
Pretty big overhaul, I look forward to the result!

Why not call it 1.0? Also, if you want to have a nice blog on our site about this release, please shoot me an email! I'd love to promote it a bit.

**Comment by dartcafe** [comment]
> Why not call it 1.0? Also, if you want to have a nice blog on our site about this release, please shoot me an email! I'd love to promote it a bit.

There is some work to do until 1.0. This release is nearly ready. A blog post could be a nice idea. I will contact you.

**Comment by dartcafe** [comment]
So. I have no more desire on working on this release. I will make an RC1-tag and prerelease with the current status. Release will come shortly, after arrangement together with @v1r0x. If no critical issues occur, I would like to release this. Lot of work is comming up.

Note: Due to using some of some functions, which were introduced with NC14, this release will only support NC14.

**Pull request merged**
