### PR TITLE
add excel and csv download

### LINKED ISSUE #366: export poll
### Steps to reproduce
1.open the poll inFirefox
2.press CTRL A, CTRL C
3.paste the result in libreoffice calc

### Expected behaviour
the selected options should be visible in calc for example with a 0 for not sure, a 1 for taking part and a -1 for not taking part

### Actual behaviour

The selected options are not in the clipboard

### Alternative solution
add an export to csv functionality

### LINKED ISSUE #1942: (Excel-)Download
I would like to be able to download an export of a poll with a matrix of the dates or options on the horizontal axis and the names and e-mails of the participants on the vertical axis e.g. in Excel-Format or csv that is importable in Excel.

Doodle has a similar feature.

grafik

### PR DESCRIPTION
**Pull request by dartcafe**
resolves #366 
resolves #1942 
first implementation 
* using sheetJS (aka xlsx) and file-saver
* allow Download of excel, ods, html and csv formats
* Added admin feature toggle 
## GUI
grafik

## Excel result
grafik

# CSV-Export

```csv
Date option,,,,,,,,,
"When would it be the best time, we meet?",,,,,,,,,
from,"Mon, Jul 5, 2021 12:00 AM","Tue, Jul 6, 2021 12:00 AM","Tue, Jul 13, 2021 2:20 AM","Tue, Jul 13, 2021 3:00 AM","Wed, Jul 14, 2021 11:00 AM","Tue, Jul 20, 2021 6:00 AM","Tue, Sep 14, 2021 12:00 AM","Mon, Oct 11, 2021 12:00 AM","Sun, Oct 31, 2021 12:00 AM"
to,"Tue, Jul 6, 2021 12:00 AM","Wed, Jul 7, 2021 12:00 AM","Tue, Jul 13, 2021 2:20 AM","Tue, Jul 13, 2021 6:00 AM","Wed, Jul 14, 2021 12:00 PM","Thu, Jul 22, 2021 6:00 AM","Wed, Sep 15, 2021 12:00 AM","Thu, Oct 14, 2021 12:00 AM","Mon, Nov 1, 2021 12:00 AM"
Juller,✔,❌,✔,✔,✔,✔,✔,,
Juppppppp,✔,✔,✔,✔,✔,,,,
Pater Noster,,,,,,✔,,✔,
aa,✔,,,,,,,,
Dartcafe,❌,❌,✔,❌,❌,❔,,,

```

### CODE REVIEW

**Comment by mamo2021** [comment]
Seems to be great!
Thanks for your work!
I think it would be perfect if it was possible to add lines at the end with sums of each choice-type, so the user would be directly able to compare the options.

Example:
;Choice1;Choice2;...
yes;10;0;...
maybe;5;3;...
no;0;10;...

**Comment by clawoflight** [comment]
@mamo2021 Then it's no longer a simple table though, and much harder to work with (e.g. not equivalent to the CSV).
You could trivially write some excel formula to calculate whatever you want, that's maybe better?

**Comment by dartcafe** [comment]
> I think it would be perfect if it's possible to add lines at the end with sums of each choice-type, so the user would be directly able to compare the options.

Of course, everything is possible, but
1) it is the first iteration and
2) every coding line has its price. 

I think the idea behind an excel export is, that you have the right tool to do with the data, what ever you like. 

More improvement will come for sure and every idea is welcome.

**Review by Valdnet — APPROVED** [review]

**Comment by baschni** [comment]
Hi!

Could you please add user e-mails to the export (as was asked in #1942), because username can be changed by user as liked and is not enough to distinguish between users.

Kind regards
Bastian

**Comment by dartcafe** [comment]
Do not comment closed issues, comments can get lost or overseen. Just open a new feature request: 
https://github.com/nextcloud/polls/issues/new?assignees=&labels=&template=feature_request.md

**Comment by baschni** [comment]
Ah, then I just was too late that 1942 was closed :/

**Comment by dartcafe** [comment]
Yeah, I missed that e-mail detail.

**Comment by t-markmann** [comment]
Hi, thank you for this cool feature.
I'm currently trying to build the latest master to get this feature to production, but I can't get it to work.

Can you estimate when the next release (including this feature) will be in the nextcloud appstore?

**Comment by dartcafe** [comment]
See beta release.

**Comment by Coernel82** [comment]
Thank you very much for your work!

**Pull request merged**
