### PR TITLE
Move transifex config for updated l10n script

### PR DESCRIPTION
**Pull request by MorrisJobke**
See nextcloud/docker-ci#78 for details

Signed-off-by: Morris Jobke <hey@morrisjobke.de>

### CODE REVIEW

**Comment by dartcafe** [comment]
@MorrisJobke A Question: Are new translation strings recognised automatically by transifex or have I to add them manually to the translation files?

**Comment by dartcafe** [comment]
@MorrisJobke To clarify: We have new translations strings inside our vue files, but I don't see transifex taking them. Did I do a mistake?

**Comment by MorrisJobke** [comment]
> @MorrisJobke A Question: Are new translation strings recognised automatically by transifex or have I to add them manually to the translation files?

This should be done automatically.



> @MorrisJobke To clarify: We have new translations strings inside our vue files, but I don't see transifex taking them. Did I do a mistake?

Do you have a specific one for me, so I can check the logs ;)

**Comment by dartcafe** [comment]
For example: 
https://github.com/nextcloud/polls/blob/8a2dbd562971e70fe5268e32e7d19757ba2867bf/src/js/Create.vue#L108

**Comment by dartcafe** [comment]
Does the robot only scan the master branch?

**Comment by MorrisJobke** [comment]
Yes - only master is fetched

**Comment by MorrisJobke** [comment]
This commit also seems to be in no branch.

**Comment by dartcafe** [comment]
Which commit do you mean?

**Comment by MorrisJobke** [comment]
The example you linked.

But it is also on master it seems:

https://github.com/nextcloud/polls/blob/master/src/js/Create.vue#L108

**Comment by MorrisJobke** [comment]
Ah right - polls app. There was an issue with the sync run. Let me check it. It seems that there is a broken translation.

**Comment by MorrisJobke** [comment]
Found the issue: I missed to update the container and then it contained the old extractor that couldn't ignore the generated files and thus created wrong translation files.

**Comment by MorrisJobke** [comment]
Works now: be03d1e2af635de7267fec561483e8ecdf315a6c

Sorry for this. I had it on my todo list, but it was pushed down.

**Comment by dartcafe** [comment]
Happens. No Problem. And thanks for caring.

**Pull request merged**
