### PR TITLE
Fix: sidebar archive poll

### LINKED ISSUE #3563: Archive poll behaves differently
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Buttons `Archive poll` in Right Sidebar and Poll list (under three-dot menu) are behaving differently:

https://github.com/nextcloud/polls/blob/1954dab1a73099209279980d16a6665f794c659d/src/js/views/PollList.vue#L233-L239

https://github.com/nextcloud/polls/blob/1954dab1a73099209279980d16a6665f794c659d/src/js/components/SideBar/SideBarTabConfiguration.vue#L167-L174

### What did you expect, how polls should behave instead?

Both should dispatch `poll/toggleArchive`

### What steps does it need to replay this bug?

1. Create a poll
2. Check request from Right Sidebar
3. Check request from Poll list

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

17-master (maybe earlier)

### Which browser did you use, when experiencing the bug?

- [ ] Firefox
- [X] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

_No response_

### Add your browser log here

_No response_

### Additional client environment information

_No response_

### NC version

Nextcloud 29

### Other Nextcloud version

_No response_

### PHP engine version

PHP 8.0

### Other PHP version

_No response_

### Database engine

MySQL

### Database Engine version or other Database

_No response_

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

_No response_

### Additional environment informations

_No response_

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
Fix #3563

### CODE REVIEW

**Review by dartcafe — APPROVED** [review]
Nice find. Looks gut. But it is not a bug, just a refactoring. 

Thanks for caring

**Comment by Antreesy** [comment]
> Thanks for caring

Hi, René @dartcafe ! Could I ask you about the timeframe this changes could be released?

Maybe it would help if someone from the company also can assist with backports and be involved to prepare and roll out releases? Let us know, what do you think of this suggestion, thanks!

**Comment by dartcafe** [comment]
This is a minor issue, but will be available with the next release. 

But what difference does user see?

**Comment by Antreesy** [comment]
> But what difference does user see? 

User could not archive a poll via button 'Archive poll' in sidebar, as it was not reaching the correct API endpoint...
I still don't see, how this is a refactoring and not a bugfix, as UX is broken for an end user.

**Comment by dartcafe** [comment]
I cannot confirm this with 7.1.1. Both archiving functions change the archiving attribute as they are literally doing the same. 
Both functions are doing the same. Prior the method inside the sidebar changes the `deleted` attribute. 

After the change the store offered function changes the `deleted` attribute. It was just an inconsistent usage. 

Or do I miss something?

**Comment by dartcafe** [comment]
BtW: The `backport reminder` is just a tag for me to make sure, that the changes are ported to the vue3 branch.

**Comment by Antreesy** [comment]
Then something isn't working the same on backend. I see that deleted param is passed, although change isn't saved, and after page reload it returns a non-deleted poll:
https://github.com/nextcloud/polls/blob/2c06331c53fe64d0ca619f125e06bd3ff45b861b/lib/Service/PollService.php#L217
image
image

It behaves differently from `toggleArchive` endpoint:
https://github.com/nextcloud/polls/blob/2c06331c53fe64d0ca619f125e06bd3ff45b861b/lib/Service/PollService.php#L267
image

**Comment by dartcafe** [comment]
Unfortunately you didn't tell, which polls version you are using.

**Comment by Antreesy** [comment]
> Unfortunately you didn't tell, which polls version you are using.

"polls": "7.1.1"

**Comment by dartcafe** [comment]
I did a fresh install from the appstore and everything works as expected. Both, archiving from the polls list as well as from the navigation. 

Anyway, the new version is on the way and any alalysis is more academic than effective. 😉

**Pull request merged**
