### PR TITLE
Updated vote page design

### PR DESCRIPTION
**Pull request by dartcafe**
To dos
- [ ] finish the side bar
- [x] optimize CSS design
- [x] get public vote working (js error with avatar)
- [x] get public vote working on small devices
- [ ] create tests(?)
- [x] add changes based on discussion
- [ ] ...

### CODE REVIEW

**Comment by joergmschulz** [comment]
Pretty good stuff seems to approach here.
Personally, I don't like the sloped 'Bestes Ergebnis'; it's too flashy.
When scaling windows of Text polls, some headlines (those with only 1 line) vanish; reproducible for Firefox/Safari (OSX Sierra)

**Comment by dartcafe** [comment]
Hehe. I was just playing, and didn't want to leave this. It would break the nc desing a little bit. Work is still in progress.

**Comment by dartcafe** [comment]
I broke the comments somewhere. Will investigate later. Open for comments. The sidebar is not ready right now, and I am not sure if this is a good solution. 
The polls page should work now, Responsible layout is a todo too.

**Comment by splitt3r** [comment]
Why did you manually edit the l10n files? I think transifex will override your changes.

**Comment by dartcafe** [comment]
I just copied them from the master branch to this one. The merging conflict disturbed me.

**Comment by splitt3r** [comment]
Very nice Idea 😄 but voting and commenting don´t work for me and the author info looks a bit strange:

Vote page

**Comment by dartcafe** [comment]
I had an error in the js, which terminates the `document.ready` function. I fixed it. The side bar isn't finished right now. This will be the next step.

**Comment by dartcafe** [comment]
Updated the redesign. There are some art work and some minor fixes to do, but nearly I finished the structure change to flexbox. Goal was to create some structure, which is able to react responsible. 

I also switched the counter and the winner indicator to the top. It is not yet beautiful, but nearly, what I wanted to get. So please comment this. 

Don't look on the side bar details, they are object of the next step. But what do you think about moving details and the comments to it? 

I will add the to dos into the starting comment.

bildschirmfoto vom 2017-10-31 um 11 13 18
bildschirmfoto vom 2017-10-31 um 11 19 13
bildschirmfoto vom 2017-10-31 um 11 18 35
bildschirmfoto vom 2017-10-31 um 11 19 02

**Comment by splitt3r** [comment]
Awesome work! I think the mobile view looks a bit strange. The grey background behind the result icon should somehow have some space between the different rows.

**Comment by Ludovicis** [comment]
Hello,
"But what do you think about moving details and the comments to it?"

I agree to put the details and comments in the sidebar, i think it's more clear, 
less load on the poll screen. Nice work on the new design, I appreciate it

**Comment by dartcafe** [comment]
Some updates
bildschirmfoto vom 2017-11-01 um 09 23 41
bildschirmfoto vom 2017-11-01 um 09 22 36
bildschirmfoto vom 2017-11-01 um 09 23 33
bildschirmfoto vom 2017-11-01 um 09 23 01
bildschirmfoto vom 2017-11-01 um 10 08 46

**Comment by splitt3r** [comment]
Small bug 😀:

Date

**Comment by v1r0x** [comment]
Very nice work! :tada: 

One small issues I encountered:
- I'd replace the `click` with a `toggle` for the side bar button. Thus it would be possible to also hide the side bar with a click on the cog button.

**Comment by dartcafe** [comment]
As far as I see, all known bugs are eleminated and the design change is finished. Feel free to test and report bugs. 

Any suggestions welcome. 
BTW: I switched the winner's highlighting. Maybe someone has a good idea how to make it better. 
Also the side bar's switch is not the optimal solution in my opinion.

**Comment by dartcafe** [comment]
@v1r0x 

> Is it on purpose to display the times in UTC? IMO this should be in the user's timezone.

Hehe. Of course not. I changed some classes and so the js didn't work. Fixed.

> I'd replace the `click `with a `toggle `for the side bar button. Thus it would be possible to also hide the side bar with a click on the cog button.

Yep. Something I thougt about and forgot. 🤣 I'll change this later.

**Comment by jancborchardt** [comment]
Can we get rid of the white and grey lines between the colored fields? Would look much cleaner then. :) Also, there should be a bit more padding on each row so that the height is at least 44px.

**Comment by joergmschulz** [comment]
After going from the sidebar to edit, I managed to screw up an old poll: entries got duplicated for an anonymous poll:
grafik

**Comment by dartcafe** [comment]
This bevaior of the edit page is not depending of the page you enter it from. I can reproduce it even from the list page. Will inspect this on another PR/branch.

**Comment by dartcafe** [comment]
I commited the final changes and would like to merge. Anny fixes can be done in another PR. This one is getting too big.

**Comment by splitt3r** [comment]
We should add a develop branch or sth. like that so the master remains stable after merging sth. like this. What do you think @v1r0x @dartcafe?

And this looks a bit strange:

Polls

Why is the author info in the sidebar gone?

**Comment by joergmschulz** [comment]
Nooo, some css seems to be missing? 
grafik

**Comment by splitt3r** [comment]
Clearing the cache should solve that 😛

**Comment by dartcafe** [comment]
@splitt3r box-sizing added.
@joergmschulz A forced reload should help.

**Comment by dartcafe** [comment]
I also think, we need a dev-branch, so important fixes can go to the master, when serveral PRs can be merged to the dev-branch. I will create one, and merge this PR to that.

**Comment by splitt3r** [comment]
https://github.com/nextcloud/polls/blob/votepage-design/templates/main.tmpl.php#L167 what´s that :D?

**Comment by dartcafe** [comment]
> https://github.com/nextcloud/polls/blob/votepage-design/templates/main.tmpl.php#L167 what´s that :D?

oops. 😄

**Comment by dartcafe** [comment]
@joergmschulz Edit exising polls should work now. 
@v1r0x We have to review the comparisons, because strict comparison is not possible. I am not sure if this is essential, but it is recommended in the style guides.

**Comment by splitt3r** [comment]
I could have a look at the comparism in #179.

**Comment by dartcafe** [comment]
If there ar no more issues, I would like to merge with `develop`.

**Comment by splitt3r** [comment]
@dartcafe you reverted all my unit test changes in the dev branch? any reason for that? For example https://github.com/nextcloud/polls/tree/develop/tests/Unit/

**Comment by dartcafe** [comment]
Äh. Nope, no reason. I didn't notice, that I did that. Can it be restored?

**Comment by dartcafe** [comment]
Ah. Maybe I made a mistake, when I wanted to downstream the changes in develop to the other branch. 
Grrr.. Sorry. Obviosly, I didn't foresee my doing..... Any chance to fix/revert that?

**Comment by splitt3r** [comment]
No problem the changes are still available in the cleanup branch i will have a look at it later.

**Comment by dartcafe** [comment]
OK. Sorry again. As far as I see, i mixed it up a little bit. I will inspect later, what happened, because I have to understand this.

**Comment by splitt3r** [comment]
I tried to fix it https://github.com/nextcloud/polls/tree/cleanup here could you check if it´s correct now?

**Pull request merged**
