### PR TITLE
Vue refactoring

### PR DESCRIPTION
**Pull request by dartcafe**
some refactoring of the complete vue app and initial setup for 1.5
❗  Please rebase your current branches after this is merged to master

* fixing of style issues
* got rid of some terrible CSS constructions
* moved colors and icons to root variables

* merged some components to avoid double code
* cleanup store (some more consolidation is a to do)

* updated to vue-nextcloud 2.0
* using more @nextcloud-modules 
* updated dev dependencies
* updated linter config
* updated polls version to 1.5.0

* load a poll in one request
* make sidebar available in poll list
* added in-/decremet buttons for moving date options

### CODE REVIEW

**Comment by dartcafe** [comment]
@v1r0x Do you have time to make a review? Otherwise I would take the risk to merge this, so the development can continue.

**Comment by v1r0x** [comment]
I had a quick look at the code changes and didn't see anything bad. I'll try to give it a real test today or tomorrow.
IMO we shouldn't merge without testing, because 1.5.0 indicates a very stable version.

**Comment by v1r0x** [comment]
Had no time to test this weekend. Will do some tests this week.

**Comment by v1r0x** [comment]
When installing this branch I get a blank page and this error message:

```
The resource from “http://localhost/nextcloud/index.php/apps/files/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by dartcafe** [comment]
??? never saw this. I try a fresh install from the branch later.

**Comment by dartcafe** [comment]
Did a fresh build on debian with fresh
* git clone polls
* npm install -g npm (for update to newest version of npm)
* npm install
* make appstore

after that I uploaded [polls.tar.gz](https://github.com/nextcloud/polls/files/4640650/polls.tar.gz) and activated (polls was not installed before). 
No errors...

**Comment by v1r0x** [comment]
That's weird.,..I'll try again on a clean setup

**Comment by v1r0x** [comment]
Using the `tar.gz.` from `make appstore` works fine. When cloning it directly into the apps directory and run `make dev-setup` it doesn't work. In the past this way worked fine :confused: 

Any idea why this quicker method doesn't work in that case?

**Comment by dartcafe** [comment]
@v1r0x I have no idea. I am building locally and sync files and dirs to the remote test instance.
BTW: more PR are ready to review. :-)

**Pull request merged**
