### PR TITLE
Code cleaning

### PR DESCRIPTION
**Pull request by dartcafe**

### CODE REVIEW

**Comment by dartcafe** [comment]
@splitt3r I activated travis CI. Because I don't have a glue how to use it proper: Please check, if it works as expected.

**Comment by splitt3r** [comment]
Thx 👍 https://travis-ci.org/nextcloud/polls it works!

**Comment by dartcafe** [comment]
OK. Now that it works: What can we do with it? ;-)

**Comment by splitt3r** [comment]
Run the unit tests on every commit / pr and e.g. check code quality. You can check out other nextcloud apps to see what they are doing with Travis CI.  Most of them also use the [Drone CI](https://drone.nextcloud.com/).

**Comment by dartcafe** [comment]
Especially code quality is something, what gets important. The challenge will be to write the unit test, something, I am not aware of. The tool seems to be nice, but a fool with a tool is still a fool. :-). 

Scrutinizer is for code quality, right?

**Comment by dartcafe** [comment]
I mean code style quality.

**Comment by splitt3r** [comment]
Yep. Awesome :)

**Comment by splitt3r** [comment]
You could also try to add transifex to this repo :muscle:

**Comment by dartcafe** [comment]
Ok scrutinizer is up and running. I am playing with it a little bit.

**Comment by splitt3r** [comment]
If you take the .scruntinizer.yml and the .jshintrc from the calendar app it should recognize all the OC JS globals.

**Comment by dartcafe** [comment]
Scutinizer is cool, but they offer no free plan. So 50 € per month is nothing we can afford... :-( Are there alternatives, because, the hints are very useful.

**Comment by splitt3r** [comment]
What about open-source repositories?

We do not charge for open-source repositories, you can add as many as you like.

**Comment by dartcafe** [comment]
Haven't found any hint on free plans for OS project. You have a source?

**Comment by splitt3r** [comment]
https://scrutinizer-ci.com/pricing mobile it's in the end of the page.

**Comment by dartcafe** [comment]
OMG. I am blind. 🙈 👌

**Comment by splitt3r** [comment]
@dartcafe you should exclude the datetimepicker from scruntinizer. Perhaps also add it as some kind of package manger dependency?

**Comment by dartcafe** [comment]
Same thought by me. 👌

**Comment by dartcafe** [comment]
@v1r0x I would like to merge this PR, because it got huge. 
I found some functions declarations in the PageController, which seem not to be used. I commented them out and marked them as not used. Can you confirm that?

**Comment by splitt3r** [comment]
Commenting out is not the git way :grimacing: better delete them and we can revert it

**Comment by v1r0x** [comment]
@dartcafe Looks like all of them are in use.
- `getGroups()` is used in `hasAccess()`
- `getPollsForUserWithInfo` is used in `index()`
- The search functions are used in `create_edit.js` as AJAX calls.

Maybe not best practice, but it works for now. IMO we should keep them and merge the PR. Removing/Replacing them can then be done in a future PR/release.

**Comment by dartcafe** [comment]
@v1r0x You are right with getGroups(), I cleaned my glasses. But getPollsForUserWithInfo is not found anywhere in the app. I didn't expect the search functions in the js. Great hint. In the end I will keep the functions for now. We can investigate later. 

I can squash them. Makes sense. In the end I would like to convert all space indents to tabs. This saves some thousend bytes.

I will do the last commits later this day. Feel free to merge then, so I can continue inspeting based on the scrutinizer hints.

@splitt3r: The commenting was for checking. So I can revert it better, insted of reverting commits. I didn't want to keep them, because this would be waste of space.

**Comment by dartcafe** [comment]
Please review and merge if you mind.

**Comment by v1r0x** [comment]
@dartcafe You are right `getPollsForUserWithInfo` is not in use.

Feel free to merge, squash would be good :)

**Pull request merged**
