### PR TITLE
datetimepicker.js Update to version 2.5.14

### PR DESCRIPTION
**Pull request by dartcafe**

### CODE REVIEW

**Comment by splitt3r** [comment]
Let´s move the dependencyto an package.json and pass the oC locale to it like https://github.com/xdan/datetimepicker#datetimepicker.

**Comment by joergmschulz** [comment]
something seems to be missing:
grafik

**Comment by dartcafe** [comment]
The vendor dir was excluded in .gitignore, so the css did not make it's way into the repo. Fixed...

**Comment by dartcafe** [comment]
@splitt3r This sounds like bohamian villages to me. 😀 How is this done?

**Comment by dartcafe** [comment]
On the other hand, I would like to replace this datepicker with the one in core. The time picker can be omittet after redesign.

**Comment by splitt3r** [comment]
But the one in core has no time selection?

**Comment by splitt3r** [comment]
If we would introduce an ui like the doodle one, the core datepicker / timepicker would work perfectly fine 💪.

**Comment by dartcafe** [comment]
No, we will make it better. We will not copy doodle. I want to see them copying us.

**Pull request merged**
