### PR TITLE
Quick fix for displaying dates in IE and Safari

### PR DESCRIPTION
**Pull request by dartcafe**

### CODE REVIEW

**Comment by dartcafe** [comment]
Fixes the date display in Safari and IE. But on Firefox mobile it is still broken.

**Comment by joergmschulz** [comment]
for  my Safari: Not really. Now the dates are not shown at all 👎 I try to retest tonight with more time

**Comment by dartcafe** [comment]
Hmmm. I only tested on an iPad. You have a Mac? Are you able to debug the vote.js?

**Comment by joergmschulz** [comment]
You are right --- when I pull #139  and then apply the change of #138 it seems to work. Will verify tonight with IE. 👍 YOU MADE MY DAY

**Comment by dartcafe** [comment]
Äh. OK. Strange, #139 has nothing to do with #138. Maybe something was cached...

**Comment by joergmschulz** [comment]
Comprehensive tests with Safari and Firefox of #138 along with #139 are very promising. GUI looks nice, date and text polls work as they should including duplicate text alternatives and group permissions.
I didn't do a complete test of all functions using all browsers yet - but the critical issues I've learned about have been covered. 
Can somebody pls test on mobile devices like tablets / iPads? 
Other than that, I would suggest this pr should be approved soon, @v1r0x ?

**Comment by dartcafe** [comment]
Firefox on iOS is OK also, als Chrome and Safari.

**Comment by dartcafe** [comment]
New PR in #144

**Pull request closed without merging**
