### PR TITLE
Update pr-feedback workflow

### PR DESCRIPTION
**Pull request by marcelklehr**

### CODE REVIEW

**Review by dartcafe — APPROVED** [review]

**Comment by dartcafe** [comment]
@marcelklehr Is it by intention, that all my PRs are now catched? 😉

**Comment by marcelklehr** [comment]
heh, yes and no. There's an opt out list: https://github.com/nextcloud/polls/blob/master/.github/workflows/pr-feedback.yml#L33

**Comment by dartcafe** [comment]
🤣 You are sraping the teams site for that? Nice.
Thanks for pointing me to that. I hope there will be no updates to the action, so I don't have to add me again after.

**Comment by dartcafe** [comment]
@marcelklehr 
Not funny in the future
grafik
From https://github.com/nextcloud/polls/pull/3456

**Comment by dartcafe** [comment]
Maybe a local configuration makes sense

**Pull request merged**
